### ISSUE TITLE
Changes to products feed?

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#11]
I think the products feed stopped working correctly.

Even though it is returning data the "last_id" and "per_page" options are not working.

**Comment by Dayjo** [comment]
Hi @robertoldaker 

We've not made any changes in relation to the last id or per page options. I shall see if I can replicate the problem!

**Comment by Dayjo** [comment]
Hi @robertoldaker,

I believe I've resolved this issue, those filters should now be working! Sorry for the inconvenience!

**Comment by robertoldaker** [comment]
Its working again now!

**Comment by Dayjo** [comment]
Great, thanks Rob!

**Comment by robertoldaker** [comment]
Are you doing more development on the api?  Please let me know if\when new
features become available.

**Comment by Dayjo** [comment]
We'll be formalising the road map for the API shortly, will keep you posted!
