### ISSUE TITLE
The "order products" feed does not show what product options were selected by the customer.

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#3]

**Comment by Dayjo** [comment]
This is undecided as to whether they should be included within the product item as sub items or be a separate request. 

It's probably nicer if it's just included within the product item.

**Comment by Dayjo** [comment]
Hi Rob,

I've done a fix for this which hopefully I'll be able to test and release tomorrow. 

It will change the options element of an order/product into an object like so;
```
 options: {
    71099: { // Unique ID for the Option
        name: "Label Pack Size",
        value: "5 Sheets",
        custom_value: null
   }
}
```

How does this work for you?

**Comment by robertoldaker** [comment]
Hi Joel,

Its not ideal since a database id is being used as a json variable name
(e.g. 71099). To perform the json to c# mapping I create classes that need
fixed variable names.

Ideally I would like an array of options e.g.
options: [
{
     name: "pack size",
     value: "small",
},
{
     name: "colour",
    value: "red"
}
]

What do you think?

Rob.

**Comment by Dayjo** [comment]
To allow us the full scope of the options system, I think it should probably be more like;

```js
options: [
{
     ID: 71099,
     name: "pack size",
     items: [
         {
              ID: 12584,
              value: "small",
              custom_value: null
         }
         ...
    ]
}
...
]
```

The reason for making `items` an array is while currently it's not possible, some day we might allow a product option with multiple options (i.e. a checkbox list, or multi select box) This is much closer to the true structure of the options and ensures the full information from the order.

You should be fine with just using `items[0]` to get the selected item from the option.

**Comment by robertoldaker** [comment]
That's fine by me.

**Comment by Dayjo** [comment]
Hi Rob,

This has now been put into production, please let me know if it's working for you and close the issue if you're happy!

**Comment by Dayjo** [comment]
I have updated the Documentation accordingly; http://developers.create.net/API-Documentation/resources/shop/order_managment/order_products.html

**Comment by robertoldaker** [comment]
Hi Joel,

I don't think its working where there are more than 1 product option for a product.

This is a snippet of the json returned for sale 1948564 and the product "(125033)  Organic & Fairtrade Shea Butter (Refined / Unrefined)". This product has two options "g" and "refined / unrefined".

"options":
[
{"ID":71248,"name":"g","items":
           [{"ID":378974,"value":"100g","custom_value":""}]},
{"ID":78908,"name":"Refined \/ Unrefined","items":
           [{"ID":378974,"value":"100g","custom_value":""},
            {"ID":2741018,"value":"Unrefined (Cream)","custom_value":""}]
}],

As you can see the second option is returning 2 items for the options value (which shouldn't happen!). It looks like it's erroneously inserting the value for the first option.

Rob.

**Comment by Dayjo** [comment]
Hi Rob,

Apologies, I've resolved that issue for you.

**Comment by Dayjo** [comment]
Hi Rob,

Quick update on this,  I'm changing the 'value' key on an item to be 'title' as it's a more accurate representation of a product option item, and will be replicated across the `/Products` model too. 

So it'll now look like;;
```js
options: [
{
     ID: 71099,
     name: "pack size",
     items: [
         {
              ID: 12584,
              title: "small",
              custom_value: null
         }
         ...
    ]
}
...
]
```

**Comment by robertoldaker** [comment]
OK - thanks for letting me know.

rob.

**Comment by Dayjo** [comment]
On top of that, for consistency, I will be changing option.name to be title also, although this probably won't happen until Monday.

I figure we may as well use the same terminology across each thing that has a 'title/name/etc', this is the internal terminology too. Just when the documentation was written it was changed to 'name'. 

I will keep you posted.
