### ISSUE TITLE
Order Status

### ISSUE THREAD

**Issue by sparkweb** [createdotnet/API-Documentation#30]
Hi, could we get some documentation for the various order statuses? The docs specify that they are integers, but I don't see any docs about which numbers match up to which status.

**Comment by EdBailey** [comment]
Hi there,
This is one of the places I've been meaning to improve the documentation so I'm glad you asked.

The following is the meaning of each status/sub_status:
 - `status` 1 - Pending
   - `sub_status` 1 - Waiting Payment
 - `status` 2 - Processing
   - `sub_status` 1 - Picking
   - `sub_status` 2 - Packaging
   - `sub_status` 3 - Waiting Dispatch
 - `status` 3 - Dispatched
 - `status` 4 - Refunded
 - `status` 5 - Cancelled

I hope this is helpful and I shall get these details added to the documentation
