### ISSUE TITLE
How about a new "Test" method?

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#4]
This would simply return "OK" if the supplied token is valid, or the normal error message if the token is invalid. This would be used when configuring the api to check that comms to the server is working ok and that token is valid.

**Comment by Dayjo** [comment]
Great suggestion!

**Comment by Dayjo** [comment]
Hi @robertoldaker,

You'll be happy to know this has now been implemented: http://developers.create.net/API-Documentation/resources/general/test/test.html
