### ISSUE TITLE
Problem with caching?

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#5]
The api seems to cache the results. e.g. If I use one token to get a product feed and then swap to another one its returning the same results.

I turned off all local caching and set the http header value "cache-control" to "no-cache" to force the request to the server but I still had the same results.

What did work however was to add a random, dummy query string value (e.g. "products?random=1234567").

**Comment by Dayjo** [comment]
Interestingly I cannot replicate this. Is this in the browser (and if so, which browser), or done within code?

In the browser I used my token to get my products, i.e. go to; https://api.create.net/products. I then changed my token, refreshed the page and the response updated correctly with the other site's products.

Just did that with both of the tokens you're using as well and it appeared to work correctly.

**Comment by robertoldaker** [comment]
I used the c# .net http library. When you make a request it comes back with
a boolean saying whether it took it from the local cache or not - it always
returned saying it didn't.

How did you use your browser for this (apologies for my ignorance)? I am
not sure how to set http header values. Would be a good test as it would
show whether the client library is at fault.

**Comment by Dayjo** [comment]
There's an extension for Chrome called PostMan which is pretty useful for REST API testing; https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en

But for just using url based calls, I use a Chrome extension called [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) to set my token like so;
![](http://cl.ly/image/2Q3J422K0B2a/Image%202015-01-16%20at%202.59.08%20pm.png)

**Comment by robertoldaker** [comment]
Thanks for that - they sound useful extensions!

**Comment by Dayjo** [comment]
No problem! Let me know if you get the same response doing it this way!

**Comment by robertoldaker** [comment]
Have tried them using chrome and there seems no caching issues - obviously
something to do with my client!

**Comment by robertoldaker** [comment]
I have tried two different http clients on ASP.NET - the official one and a third party one specific for REST apis. They both have an issue with caching that can only be fixed by adding a dummy query value with a random value.

Would it be possible to add a http header with name "Cache-Control" and value of "no-cache"  to the response?

**Comment by Dayjo** [comment]
Hi @robertoldaker,

We've added no-cache to the header, see if that helps!

**Comment by robertoldaker** [comment]
Is this mod live?

**Comment by Dayjo** [comment]
Yeah this is live. Here are the headers I now get;

```
Accept-Ranges:bytes
Age:0
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Length:3542
Content-Type:application/json
Date:Mon, 19 Jan 2015 11:22:57 GMT
Server:nginx/0.7.67
Vary:Accept-Encoding
Via:1.1 varnish
X-Backend:webnode02
X-Varnish:301043276
```

**Comment by robertoldaker** [comment]
Still getting the caching problem.

Will revert to adding the dummy query variable for want of a better
solution.

Must be something low-level in .Net that is shared by both client libraries.

**Comment by Dayjo** [comment]
Must be! Have tried via HTTPS in-browser, and through PHP with no issues with caching. 

Potentially could add a last-modified header, but no-cache should do the job if you've got local caching.
