### ISSUE TITLE
Problem with paging?

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#6]
I cannot get the paging to work. When I set the "per_page" to 50 or 100 I am always getting back 25 values. If I set "last_id" to the last item of a previous returned set of products it still returns the original set of products.

This could be related to the caching issue (5) but I did add a "random" query value to force caching off.

**Comment by Dayjo** [comment]
Hi Rob, 

Thanks for spotting this, this is definitely reproducible.

**Comment by Dayjo** [comment]
This has now been fixed, both `per_page` and `last_id` should work as expected!

**Comment by robertoldaker** [comment]
Yes - I can they work now  (btw. max appears to be 99 not 100!)

**Comment by Dayjo** [comment]
Hi Rob,

Which command are you using and getting 99 instead of 100?

**Comment by robertoldaker** [comment]
"products" using the token starting "8c3c1 ..." (this account has a few
hundred products)

Rob.

**Comment by Dayjo** [comment]
Hi Rob,

Have seen why this is and fix is ready to go live on Monday.

**Comment by Dayjo** [comment]
This has gone live, 100 should now return 100.

**Comment by robertoldaker** [comment]
Works for me now!
