### ISSUE TITLE
"parent_category" property of a "product" is missing?

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#7]
How do a i find the category that a product belongs to? 

The documentation says there is a property called "parent_category" which is the id of the  category that the product belongs to. 

However this property appears to be missing when I perform a product feed. There is a property called "parentcat_INC" but that is always 0.

**Comment by Dayjo** [comment]
Hi Rob,

Well spotted, again this is an issue with the models not matching the documentation, should be relatively easy to fix.

**Comment by Dayjo** [comment]
After some deliberation, the documentation here will have to change. 

The `parent_category` property will need to be an array of category ids as a product can be contained in multiple categories. I will be updating the documentation accordingly along with the fix, once we've decided on how to go about it.

**Comment by robertoldaker** [comment]
This fix isn;t a priority for us. We really need the fix for the country
and the product options (#2, #3 and #9)

Once we have them Jessica can use it to run her business and really give it
a good test.

Regards,

Rob.

**Comment by Dayjo** [comment]
@robertoldaker could you confirm if you're happy with this fix? The logical next step would be to have a category api call for category information, but at least now it's retreiving all the IDs correctly.

**Comment by robertoldaker** [comment]
I am happy with it.

Rob.

**Comment by Dayjo** [comment]
Great thanks!
