### ISSUE TITLE
Add the ability to choose the sort order direction

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#8]
Would it be possible for "orders" to return all orders with ids > last_id? This would easily allow to see what new orders are available by setting the parameter "last_id" to the last order that has been downloaded. Currently it is returning orders that have an id less than "last_id".

**Comment by Dayjo** [comment]
We did discuss which way it should be ordered, the idea being you could just get `/orders/` and get your latest orders. So you could loop through them, if you don't already have them, process them, then go to the next page, then go through the next page in the same way..

Being able to choose which way to Order the results is something we're going to be adding though :)

**Comment by robertoldaker** [comment]
No probs - I will work with it as is.

**Comment by Dayjo** [comment]
This has now been implemented! :)
