### ISSUE TITLE
billing and shipping addresses "orders" feed

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#9]
There are typeos in the json for both the "billing" and "shipping" addresses. Each of the address line fields are spelt "adress" instead of "address" e.g. "adress1" instead of "address1".

Also the country is coming back as a number e.g. "223" instead of "UK" or "United Kingdom".

**Comment by Dayjo** [comment]
These should be very straight forward to correct, good spot!

**Comment by Dayjo** [comment]
Hi @robertoldaker 

I have fixed the spelling of the address fields, still discussing the best way for us to move from using our internal country ID to an ISO country code.

**Comment by robertoldaker** [comment]
Text would be OK (as appears on the invoices generated) if that's any easier

Rob.

**Comment by Dayjo** [comment]
Hi @robertoldaker,

I believe this is now fixed! If you'd like to check it, and close the issue if you're happy!
